// Generated by gencpp from file cvfinder/conclude.msg
// DO NOT EDIT!


#ifndef CVFINDER_MESSAGE_CONCLUDE_H
#define CVFINDER_MESSAGE_CONCLUDE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cvfinder
{
template <class ContainerAllocator>
struct conclude_
{
  typedef conclude_<ContainerAllocator> Type;

  conclude_()
    : header()
    , x(0)
    , imag_x(0)
    , flag(false)  {
    }
  conclude_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0)
    , imag_x(0)
    , flag(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _imag_x_type;
  _imag_x_type imag_x;

   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::cvfinder::conclude_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cvfinder::conclude_<ContainerAllocator> const> ConstPtr;

}; // struct conclude_

typedef ::cvfinder::conclude_<std::allocator<void> > conclude;

typedef boost::shared_ptr< ::cvfinder::conclude > concludePtr;
typedef boost::shared_ptr< ::cvfinder::conclude const> concludeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cvfinder::conclude_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cvfinder::conclude_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cvfinder::conclude_<ContainerAllocator1> & lhs, const ::cvfinder::conclude_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.imag_x == rhs.imag_x &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cvfinder::conclude_<ContainerAllocator1> & lhs, const ::cvfinder::conclude_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cvfinder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cvfinder::conclude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cvfinder::conclude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cvfinder::conclude_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cvfinder::conclude_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cvfinder::conclude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cvfinder::conclude_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cvfinder::conclude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e31fa72d72fcb35f7b30b8c72ce9793";
  }

  static const char* value(const ::cvfinder::conclude_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e31fa72d72fcb35ULL;
  static const uint64_t static_value2 = 0xf7b30b8c72ce9793ULL;
};

template<class ContainerAllocator>
struct DataType< ::cvfinder::conclude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cvfinder/conclude";
  }

  static const char* value(const ::cvfinder::conclude_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cvfinder::conclude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 x\n"
"int32 imag_x\n"
"bool flag\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cvfinder::conclude_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cvfinder::conclude_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.imag_x);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct conclude_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cvfinder::conclude_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cvfinder::conclude_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "imag_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.imag_x);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CVFINDER_MESSAGE_CONCLUDE_H
