// Generated by gencpp from file cvfinder/msg_card.msg
// DO NOT EDIT!


#ifndef CVFINDER_MESSAGE_MSG_CARD_H
#define CVFINDER_MESSAGE_MSG_CARD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cvfinder
{
template <class ContainerAllocator>
struct msg_card_
{
  typedef msg_card_<ContainerAllocator> Type;

  msg_card_()
    : header()
    , flag(0)  {
    }
  msg_card_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , flag(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::cvfinder::msg_card_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cvfinder::msg_card_<ContainerAllocator> const> ConstPtr;

}; // struct msg_card_

typedef ::cvfinder::msg_card_<std::allocator<void> > msg_card;

typedef boost::shared_ptr< ::cvfinder::msg_card > msg_cardPtr;
typedef boost::shared_ptr< ::cvfinder::msg_card const> msg_cardConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cvfinder::msg_card_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cvfinder::msg_card_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cvfinder::msg_card_<ContainerAllocator1> & lhs, const ::cvfinder::msg_card_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cvfinder::msg_card_<ContainerAllocator1> & lhs, const ::cvfinder::msg_card_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cvfinder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cvfinder::msg_card_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cvfinder::msg_card_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cvfinder::msg_card_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cvfinder::msg_card_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cvfinder::msg_card_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cvfinder::msg_card_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cvfinder::msg_card_<ContainerAllocator> >
{
  static const char* value()
  {
    return "009f1a832c7659ae86467f2e17c51aaf";
  }

  static const char* value(const ::cvfinder::msg_card_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x009f1a832c7659aeULL;
  static const uint64_t static_value2 = 0x86467f2e17c51aafULL;
};

template<class ContainerAllocator>
struct DataType< ::cvfinder::msg_card_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cvfinder/msg_card";
  }

  static const char* value(const ::cvfinder::msg_card_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cvfinder::msg_card_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 flag\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cvfinder::msg_card_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cvfinder::msg_card_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_card_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cvfinder::msg_card_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cvfinder::msg_card_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CVFINDER_MESSAGE_MSG_CARD_H
